# Generated by Django 4.2.2 on 2023-06-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitterUser', models.CharField(max_length=255)),
                ('tweet', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('NM', 'Nuetral'), ('OL', 'Offensive Language'), ('HM', 'Hateful Message')], default='Not yet analysed', max_length=2)),
            ],
        ),
    ]
