# Generated by Django 4.2.2 on 2023-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='category',
            field=models.CharField(choices=[('NM', 'Nuetral'), ('OL', 'Offensive Language'), ('HM', 'Hateful Message')], default='Not yet analysed', max_length=30),
        ),
    ]
